---
- name: Check for consul.strapped
  tags: consul
  stat: path=/etc/consul/consul.strapped
  register: consul_stat
  
- name: create consul directory
  file: >
    state=directory
    path={{ item }}
    owner={{consul_user}}
    group={{consul_group}}
  with_items:
    - "{{ consul_config_dir }}"

- name: Copy Consul init.d script
  template: src=consul.initd.sh.j2 dest=/etc/init.d/consul
  notify: start consul service

- name: add consul to path through profile.d
  template: >
    src={{consul_add_path_template}}
    dest=/etc/profile.d/consul.sh
    owner=root
    group=root
    mode=0755

- name: Set consul_bootstrap fact (not strapped)
  tags: consul
  set_fact:
    consul_bootstrap: True
  when:
    - consul_leader is defined
    - consul_stat.stat.exists == False
    - inventory_hostname == consul_leader

- name: Set consul_bootstrap fact (strapped)
  tags: consul
  set_fact:
    consul_bootstrap: False
  when:
    - consul_leader is defined
    - consul_stat.stat.exists == True
    - inventory_hostname == consul_leader

- name: Set consul_bootstrap fact (not leader)
  tags: consul
  set_fact:
    consul_bootstrap: False
  when:
    - consul_leader is defined
    - inventory_hostname != consul_leader

- name: Set consol_bootstrap fact (leader undefined)
  tags: consul
  set_fact:
    consul_bootstrap: True
  when:
    - consul_leader is not defined

handlers:
 - name: start consul service
   service: name=consul state=restarted

